# declaration of function

function(get_source_directory output dir)
  set(${output} "${CMAKE_CURRENT_SOURCE_DIR}/../${dir}" PARENT_SCOPE)
endfunction()

function(get_build_directory output source_dir)
  string(TOLOWER ${CMAKE_BUILD_TYPE} CMAKE_BUILD_TYPE_TOLOWER)
  set(BUILD_DIRECTORY "build-${CMAKE_BUILD_TYPE_TOLOWER}")
  set(${output} "${${source_dir}}/${BUILD_DIRECTORY}" PARENT_SCOPE)
endfunction()

function(get_local_library_directory_named output source_dir lib_dir)
  string(TOLOWER ${CMAKE_BUILD_TYPE} CMAKE_BUILD_TYPE_TOLOWER)
  get_build_directory(build_dir ${source_dir})
  if(MSVC)
    set(${output} "${build_dir}/${lib_dir}/${CMAKE_BUILD_TYPE_TOLOWER}" PARENT_SCOPE)
  else()
    set(${output} "${build_dir}/${lib_dir}" PARENT_SCOPE)
  endif()
endfunction()

function(get_local_library_directory output source_dir)
  get_local_library_directory_named(output_to_reassign ${source_dir} "lib")
  set(${output} ${output_to_reassign} PARENT_SCOPE)
endfunction()

function(set_dll_properties target)
  if(WIN32 AND BUILD_SHARED_LIBS)
    set_target_properties(${target} PROPERTIES PREFIX "" SUFFIX .dll IMPORT_SUFFIX ${CMAKE_IMPORT_LIBRARY_SUFFIX})
  endif()
endfunction()

function(create_osx_framework target public_headers)
  # create as a framework if build on darwin environment
  if(APPLE)
    if(BUILD_SHARED_LIBS AND FRAMEWORK)
      install(TARGETS vpvl2 DESTINATION .)
      set_target_properties(${target} PROPERTIES FRAMEWORK true PROPERTIES PUBLIC_HEADER "${public_headers}")
    endif()
    set_target_properties(vpvl2 PROPERTIES INSTALL_NAME_DIR "${CMAKE_INSTALL_PREFIX}/lib")
  endif()
endfunction()

function(vpvl2_link_bullet target)
  if(VPVL2_NO_BULLET)
    target_link_libraries(${target} ${BULLET_LINEARMATH_LIB})
  else()
    target_link_libraries(${target} ${BULLET_DYNAMICS_LIB}
                                    ${BULLET_COLLISION_LIB}
                                    ${BULLET_SOFTBODY_LIB}
                                    ${BULLET_MULTITHREADED_LIB}
                                    ${BULLET_LINEARMATH_LIB})
  endif()
endfunction()

function(vpvl2_find_bullet)
  get_source_directory(BULLET_SOURCE_DIRECTORY "bullet-src")
  get_local_library_directory(BULLET_LIBRARY_LOCAL_DIR BULLET_SOURCE_DIRECTORY)
  # find from MMDAI/bullet or environment variables
  find_path(BULLET_INCLUDE_DIR btBulletCollisionCommon.h PATHS "${BULLET_SOURCE_DIRECTORY}/src" $ENV{BULLET_INCLUDE_DIR})
  if(BULLET_INCLUDE_DIR)
    include_directories(${BULLET_INCLUDE_DIR})
  else()
    find_path(BULLET_INCLUDE_DIR bullet/btBulletCollisionCommon.h PATHS "${BULLET_SOURCE_DIRECTORY}/src" $ENV{BULLET_INCLUDE_DIR})
    include_directories(${BULLET_INCLUDE_DIR}/bullet)
  endif()
  find_library(BULLET_LINEARMATH_LIB LinearMath PATHS ${BULLET_LIBRARY_LOCAL_DIR} $ENV{BULLET_LIBRARY_DIR})
  if(NOT VPVL2_NO_BULLET)
    find_library(BULLET_COLLISION_LIB BulletCollision PATHS ${BULLET_LIBRARY_LOCAL_DIR} $ENV{BULLET_LIBRARY_DIR})
    find_library(BULLET_DYNAMICS_LIB BulletDynamics PATHS ${BULLET_LIBRARY_LOCAL_DIR} $ENV{BULLET_LIBRARY_DIR})
    find_library(BULLET_MULTITHREADED_LIB BulletMultiThreaded PATHS ${BULLET_LIBRARY_LOCAL_DIR} $ENV{BULLET_LIBRARY_DIR})
    find_library(BULLET_SOFTBODY_LIB BulletSoftBody PATHS ${BULLET_LIBRARY_LOCAL_DIR} $ENV{BULLET_LIBRARY_DIR})
  endif()
endfunction()

function(vpvl2_link_assimp target)
  if(VPVL2_LINK_ASSIMP)
    target_link_libraries(${target} ${ASSIMP_LIBRARY})
  endif()
endfunction()

function(vpvl2_find_assimp)
  if(VPVL2_LINK_ASSIMP)
    get_source_directory(ASSIMP_SOURCE_DIRECTORY "assimp-src")
    get_local_library_directory(ASSIMP_LIBRARY_LOCAL_DIR ASSIMP_SOURCE_DIRECTORY)
    get_local_library_directory_named(ASSIMP_LIBRARY_LOCAL_DIR2 ASSIMP_SOURCE_DIRECTORY "code")
    set(ASSIMP_LOCAL_INCLUDE_DIR "${ASSIMP_SOURCE_DIRECTORY}/include")
    find_path(ASSIMP_INCLUDE_DIR assimp.hpp PATHS ${ASSIMP_LOCAL_INCLUDE_DIR} $ENV{ASSIMP_INCLUDE_DIR})
    if(ASSIMP_INCLUDE_DIR)
      include_directories(${ASSIMP_INCLUDE_DIR})
    else()
      find_path(ASSIMP_INCLUDE_DIR assimp/assimp.hpp PATHS ${ASSIMP_LOCAL_INCLUDE_DIR} $ENV{ASSIMP_INCLUDE_DIR})
      include_directories(${ASSIMP_INCLUDE_DIR}/assimp)
    endif()
    find_library(ASSIMP_LIBRARY assimp PATHS ${ASSIMP_LOCAL_LIBRARY_DIR} ${ASSIMP_LIBRARY_LOCAL_DIR2} $ENV{ASSIMP_LIBRARY_DIR})
  endif()
endfunction()

function(vpvl2_link_vpvl target)
  if(VPVL2_LINK_VPVL)
    target_link_libraries(${target} ${VPVL_LIBRARY})
  endif()
endfunction()

function(vpvl2_find_vpvl)
  if(VPVL2_LINK_VPVL)
    get_source_directory(VPVL_SOURCE_DIRECTORY "libvpvl")
    get_local_library_directory(VPVL_LIBRARY_LOCAL_DIR VPVL_SOURCE_DIRECTORY)
    set(VPVL_LOCAL_INCLUDE_DIR "${VPVL_SOURCE_DIRECTORY}/include")
    find_path(VPVL_INCLUDE_DIR vpvl/vpvl.h PATHS ${VPVL_LOCAL_INCLUDE_DIR} $ENV{VPVL_INCLUDE_DIR})
    find_path(VPVL_CONFIG_DIR vpvl/config.h PATHS "${VPVL_LOCAL_BUILD_DIR}/include" $ENV{VPVL_CONFIG_DIR})
    include_directories(${VPVL_INCLUDE_DIR} ${VPVL_CONFIG_DIR})
    set(VPVL_LIBRARY_NAME vpvl)
    append_lib_type_suffix(VPVL_LIBRARY_NAME)
    find_library(VPVL_LIBRARY ${VPVL_LIBRARY_NAME} PATHS ${VPVL_LIBRARY_LOCAL_DIR} $ENV{VPVL_LIBRARY_DIR})
  endif()
endfunction()

function(vpvl2_link_glew target)
  if(VPVL2_ENABLE_EXTENSIONS_RENDERCONTEXT)
    target_link_libraries(${target} ${GLEW_LIBRARY})
    if(MSVC)
      target_link_libraries(${target} ${GLEW_MX_LIBRARY})
    endif()
  endif()
endfunction()

function(vpvl2_find_glew)
  if(VPVL2_ENABLE_EXTENSIONS_RENDERCONTEXT AND VPVL2_LINK_GLEW AND NOT VPVL2_ENABLE_GLES2)
    find_library(GLEW_LIBRARY GLEW glew glew32s PATHS ${CMAKE_CURRENT_SOURCE_DIR}/../glew-src/lib)
    if(MSVC)
      find_library(GLEW_MX_LIBRARY glew32mxs PATHS ${CMAKE_CURRENT_SOURCE_DIR}/../glew-src/lib)
    endif()
    find_path(GLEW_INCLUDE_DIR GL/glew.h PATHS ${CMAKE_CURRENT_SOURCE_DIR}/../glew-src/include)
    include_directories(${GLEW_INCLUDE_DIR})
  endif()
endfunction()

function(vpvl2_link_nvtt target)
  if(VPVL2_LINK_NVTT)
    target_link_libraries(${target} ${NVTT_NVCORE_LIBRARY} ${NVTT_NVIMAGE_LIBRARY} ${NVTT_NVMATH_LIBRARY})
  endif()
endfunction()

function(vpvl2_find_nvtt)
  if(VPVL2_ENABLE_EXTENSIONS_RENDERCONTEXT AND VPVL2_LINK_NVTT)
    get_source_directoryNVTT_SOURCE_DIRECTORY ("nvtt-src")
    get_local_library_directory(NVTT_LIBRARY_LOCAL_DIR NVTT_SOURCE_DIRECTORY)
    set(NVTT_INCLUDE_DIRECTORY "${NVTT_SOURCE_DIRECTORY}/src")
    find_path(NVTT_CONFIG_INCLUDE_DIR nvconfig.h PATHS "${NVTT_LOCAL_LIBRARY_DIR}/../src" $ENV{NVTT_CONFIG_INCLUDE_DIR})
    find_path(NVTT_BASE_INCLUDE_DIR nvcore/nvcore.h PATHS ${NVTT_INCLUDE_DIRECTORY} $ENV{NVTT_BASE_INCLUDE_DIR})
    find_path(NVTT_POSH_INCLUDE_DIR posh.h PATHS "${NVTT_SOURCE_DIRECTORY}/extern/poshlib" $ENV{NVTT_POSHLIB_INCLUDE_DIR})
    find_library(NVTT_NVCORE_LIBRARY nvcore PATHS ${NVTT_LOCAL_LIBRARY_DIR} $ENV{NVTT_LIBRARY_DIR})
    find_library(NVTT_NVIMAGE_LIBRARY nvimage PATHS ${NVTT_LOCAL_LIBRARY_DIR} $ENV{NVTT_LIBRARY_DIR})
    find_library(NVTT_NVMATH_LIBRARY nvmath PATHS ${NVTT_LOCAL_LIBRARY_DIR} $ENV{NVTT_LIBRARY_DIR})
    if (NVTT_CONFIG_INCLUDE_DIR AND NVTT_BASE_INCLUDE_DIR AND NVTT_POSH_INCLUDE_DIR)
      include_directories(${NVTT_CONFIG_INCLUDE_DIR} ${NVTT_BASE_INCLUDE_DIR} ${NVTT_POSH_INCLUDE_DIR})
    else()
      message(FATAL_ERROR "Required nvtt is not found.")
    endif()
  endif()
endfunction()

function(vpvl2_find_sfml)
  if(VPVL2_ENABLE_EXTENSIONS_RENDERCONTEXT AND VPVL2_LINK_SFML)
    find_library(SFML_GRAPHICS_LIBRARY sfml-graphics REQUIRED)
    find_library(SFML_SYSTEM_LIBRARY sfml-system REQUIRED)
    find_library(SFML_WINDOW_LIBRARY sfml-window REQUIRED)
    find_path(SFML_INCLUDE_DIR SFML/System.h)
    include_directories(${SFML_INCLUDE_DIR})
  endif()
endfunction()

function(vpvl2_find_openmp)
  if(VPVL2_ENABLE_OPENMP)
    find_package(OpenMP)
    if(OPENMP_FOUND)
      set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
    endif()
  endif()
endfunction()

function(vpvl2_link_icu target)
  if(ICU_LIBRARY_I18N AND ICU_LIBRARY_UC AND ICU_LIBRARY_DATA)
    target_link_libraries(${target} ${ICU_LIBRARY_I18N} ${ICU_LIBRARY_UC} ${ICU_LIBRARY_DATA})
  endif()
endfunction()

function(vpvl2_find_icu)
  if(VPVL2_ENABLE_EXTENSIONS_STRING)
    get_source_directory(ICU_SOURCE_DIRECTORY "bullet-src")
    get_local_library_directory(ICU_LIBRARY_LOCAL_DIR ICU_SOURCE_DIRECTORY)
    set(ICU_INCLUDE_UC_LOCAL_DIR "${ICU_BASE_DIRECTORY}/source/common")
    set(ICU_INCLUDE_I18N_LOCAL_DIR "${ICU_BASE_DIRECTORY}/source/i18n")
    find_library(ICU_LIBRARY_I18N icui18n icuin PATHS ${ICU_LIBRARY_LOCAL_DIR} "${ICU_BASE_DIRECTORY}/lib")
    find_library(ICU_LIBRARY_UC icuuc PATHS ${ICU_LIBRARY_LOCAL_DIR} "${ICU_BASE_DIRECTORY}/lib")
    find_library(ICU_LIBRARY_DATA icudata icudt PATHS ${ICU_LIBRARY_LOCAL_DIR} "${ICU_BASE_DIRECTORY}/lib")
    find_path(ICU_INCLUDE_UC_DIR unicode/unistr.h PATHS ${ICU_INCLUDE_UC_LOCAL_DIR} "${ICU_BASE_DIRECTORY}/include")
    find_path(ICU_INCLUDE_I18N_DIR unicode/regex.h PATHS ${ICU_INCLUDE_I18N_LOCAL_DIR} "${ICU_BASE_DIRECTORY}/include")
    include_directories(${ICU_INCLUDE_UC_DIR} ${ICU_INCLUDE_I18N_DIR})
  endif()
endfunction()

function(vpvl2_link_tbb target)
  if(TBB_LIBRARY_DIRS)
    target_link_libraries(${target} ${TBB_LIBRARIES})
  endif()
endfunction()

function(vpvl2_find_tbb)
  if(VPVL2_LINK_INTEL_TBB)
    find_package(TBB REQUIRED)
    link_directories(${TBB_LIBRARY_DIRS})
    include_directories(${TBB_INCLUDE_DIRS})
  endif()
endfunction()

function(vpvl2_link_zlib target)
  if(ZLIB_LIBRARY)
    target_link_libraries(${target} ${ZLIB_LIBRARY})
  endif()
endfunction()

function(vpvl2_find_zlib)
  get_source_directory(ZLIB_SOURCE_DIRECTORY "zlib-src")
  get_build_directory(ZLIB_BUILD_DIRECTORY ZLIB_SOURCE_DIRECTORY)
  get_local_library_directory(ZLIB_LIBRARY_LOCAL_DIR ZLIB_SOURCE_DIRECTORY)
  if(MSVC)
    string(TOLOWER "${CMAKE_BUILD_TYPE}" CMAKE_BUILD_TYPE_TOLOWER)
    if(CMAKE_BUILD_TYPE_TOLOWER STREQUAL "debug")
      find_library(ZLIB_LIBRARY zlibd PATHS ${ZLIB_LIBRARY_LOCAL_DIR})
    else()
      find_library(ZLIB_LIBRARY zlib PATHS ${ZLIB_LIBRARY_LOCAL_DIR})
    endif()
  else()
    find_library(ZLIB_LIBRARY z PATHS ${ZLIB_LIBRARY_LOCAL_DIR})
  endif()
  find_path(ZLIB_INCLUDE_DIR zlib.h PATHS ${ZLIB_SOURCE_DIRECTORY})
  find_path(ZLIB_INCLUDE_CONFIG_DIR zconf.h PATHS ${ZLIB_BUILD_DIRECTORY})
  include_directories(${ZLIB_INCLUDE_DIR} ${ZLIB_INCLUDE_CONFIG_DIR})
endfunction()

function(vpvl2_link_libxml2 target)
  if(ZLIB_LIBRARY)
    target_link_libraries(${target} ${LIBXML2_LIBRARY})
  endif()
endfunction()

function(vpvl2_find_libxml2)
  if(VPVL2_ENABLE_EXTENSIONS_PROJECT)
    get_source_directory(LIBXML2_SOURCE_DIRECTORY "libxml2-src")
    get_build_directory(LIBXML2_BUILD_DIRECTORY LIBXML2_SOURCE_DIRECTORY)
    if(MSVC)
      find_library(LIBXML2_LIBRARY libxml2_a PATH "${CMAKE_CURRENT_SOURCE_DIR}/../libxml2-src/win32/bin.msvc")
    else()
      get_local_library_directory(LIBXML2_LIBRARY_LOCAL_DIR LIBXML2_SOURCE_DIRECTORY)
      find_library(LIBXML2_LIBRARY libxml2 PATH ${LIBXML2_LIBRARY_LOCAL_DIR})
    endif()
    find_path(LIBXML2_INCLUDE_DIR libxml/SAX2.h "${LIBXML2_SOURCE_DIRECTORY}/include")
    include_directories(${LIBXML2_INCLUDE_DIR})
  endif()
endfunction()

function(vpvl2_find_opengl)
  if(VPVL2_ENABLE_GLES2)
    find_path(OPENGL_INCLUDE_DIR "GLES2/gl2.h")
    if(VPVL2_PLATFORM_NACL)
      find_library(OPENGL_gl_LIBRARY ppapi_gles2)
    elseif(NOT VPVL2_PLATFORM_EMSCRIPTEN)
      find_library(OPENGL_gl_LIBRARY GLESv2)
    endif()
  else()
    find_package(OpenGL REQUIRED)
  endif()
endfunction()

function(vpvl2_link_all target)
  vpvl2_link_zlib(${target})
  vpvl2_link_libxml2(${target})
  vpvl2_link_tbb(${target})
  vpvl2_link_bullet(${target})
  vpvl2_link_assimp(${target})
  vpvl2_link_glew(${target})
  vpvl2_link_icu(${target})
  vpvl2_link_nvtt(${target})
  vpvl2_link_vpvl(${target})
endfunction()
# end of functions

# imported functions from Allegro5's cmake
function(append_lib_type_suffix var)
  string(TOLOWER "${CMAKE_BUILD_TYPE}" CMAKE_BUILD_TYPE_TOLOWER)
  if(CMAKE_BUILD_TYPE_TOLOWER STREQUAL "debug")
    set(${var} "${${var}}_debug" PARENT_SCOPE)
  endif()
endfunction()
# end of imported

