pragma foreign_keys = 0;
drop table `bone_keyframe_interpolation_parameters`;
drop table `bone_keyframes`;
drop table `bone_tracks`;
drop table `bone_layers`;
drop table `camera_keyframe_interpolation_parameters`;
drop table `camera_keyframes`;
drop table `camera_layers`;
drop table `effect_keyframe_interpolation_parameters`;
drop table `effect_keyframes`;
drop table `effect_tracks`;
drop table `effect_layers`;
drop table `light_keyframe_interpolation_parameters`;
drop table `light_keyframes`;
drop table `light_layers`;
drop table `model_keyframe_ik_parameters`;
drop table `model_keyframe_interpolation_parameters`;
drop table `model_keyframes`;
drop table `model_tracks`;
drop table `model_layers`;
drop table `morph_keyframe_interpolation_parameters`;
drop table `morph_keyframes`;
drop table `morph_tracks`;
drop table `morph_layers`;
drop table `project_keyframe_interpolation_parameters`;
drop table `project_keyframes`;
drop table `project_layers`;
drop table `motions`;
drop table `model_preferences`;
drop table `models`;
drop table `project_preferences`;
drop view `motion_duration`;
pragma user_version = 0;
vacuum;

